import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHeader,
  TableHead,
  TableRow,
} from '@/components/ui/table';

export function VowelTable() {
  return (
    <section className='flex flex-col gap-4'>
      <Table>
        <TableCaption>A key for vowels</TableCaption>
        <TableHeader>
          <TableRow>
            <TableHead>Symbol</TableHead>
            <TableHead>Example</TableHead>
            <TableHead>Symbol (with R)</TableHead>
            <TableHead>Example (with R)</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow>
            <TableCell>
              <strong>ɑː</strong>
            </TableCell>
            <TableCell>
              P<strong>A</strong>LM, br<strong>a</strong>, f<strong>a</strong>
              ther
            </TableCell>
            <TableCell>
              <strong>ɑːr</strong>
            </TableCell>
            <TableCell>
              ST<strong>AR</strong>T
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>ɒ</strong>
            </TableCell>
            <TableCell>
              L<strong>O</strong>T
            </TableCell>
            <TableCell>
              <strong>ɒr</strong>
            </TableCell>
            <TableCell>
              m<strong>o</strong>ral
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>æ</strong>
            </TableCell>
            <TableCell>
              TR<strong>A</strong>P, b<strong>ag</strong>, s<strong>a</strong>ng
            </TableCell>
            <TableCell>
              <strong>ær</strong>
            </TableCell>
            <TableCell>
              m<strong>ar</strong>ry
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>aɪ</strong>
            </TableCell>
            <TableCell>
              PR<strong>I</strong>CE
            </TableCell>
            <TableCell>
              <strong>aɪər</strong>
            </TableCell>
            <TableCell>
              h<strong>ire</strong>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>aʊ</strong>
            </TableCell>
            <TableCell>
              M<strong>OU</strong>TH, h<strong>o</strong>w
            </TableCell>
            <TableCell>
              <strong>aʊər</strong>
            </TableCell>
            <TableCell>
              fl<strong>our</strong>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>iː</strong>
            </TableCell>
            <TableCell>
              fl<strong>ee</strong>ce
            </TableCell>
            <TableCell>
              <strong>ɪr</strong>
            </TableCell>
            <TableCell>
              N<strong>EAR</strong>, s<strong>er</strong>ious
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>ɛ</strong>
            </TableCell>
            <TableCell>
              DR<strong>E</strong>SS, b<strong>eg</strong>, l<strong>e</strong>
              ngth
            </TableCell>
            <TableCell>
              <strong>ɛr</strong>
            </TableCell>
            <TableCell>
              m<strong>er</strong>ry
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>eɪ</strong>
            </TableCell>
            <TableCell>
              F<strong>A</strong>CE
            </TableCell>
            <TableCell>
              <strong>eɪr</strong>
            </TableCell>
            <TableCell>
              SQU<strong>ARE</strong>, M<strong>ar</strong>y
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>ɪ</strong>
            </TableCell>
            <TableCell>
              K<strong>I</strong>T, b<strong>i</strong>g, s<strong>i</strong>ng
            </TableCell>
            <TableCell>
              <strong>ɪr</strong>
            </TableCell>
            <TableCell>
              m<strong>irr</strong>or
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>iː</strong>
            </TableCell>
            <TableCell>
              FL<strong>EE</strong>CE, l<strong>ea</strong>gue, pedigr
              <strong>ee</strong>
            </TableCell>
            <TableCell>
              <strong>ɪər</strong>
            </TableCell>
            <TableCell>
              SQU<strong>ARE</strong>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>oʊ</strong>
            </TableCell>
            <TableCell>
              G<strong>OA</strong>T
            </TableCell>
            <TableCell>
              <strong>ɔːr</strong>
            </TableCell>
            <TableCell>
              F<strong>OR</strong>CE, h<strong>oar</strong>se
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>ɔː</strong>
            </TableCell>
            <TableCell>
              TH<strong>OU</strong>GHT, c<strong>augh</strong>t
            </TableCell>
            <TableCell>
              <strong>ɔːr</strong>
            </TableCell>
            <TableCell>
              F<strong>OR</strong>CE, h<strong>oar</strong>se
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>ɔɪ</strong>
            </TableCell>
            <TableCell>
              CH<strong>OI</strong>CE
            </TableCell>
            <TableCell>
              <strong>ɔɪər</strong>
            </TableCell>
            <TableCell>
              c<strong>oir</strong>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>ʊ</strong>
            </TableCell>
            <TableCell>
              F<strong>OO</strong>T
            </TableCell>
            <TableCell>
              <strong>ʊr</strong>
            </TableCell>
            <TableCell>
              c<strong>our</strong>ier
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>uː</strong>
            </TableCell>
            <TableCell>
              G<strong>OO</strong>SE, cr<strong>u</strong>el
            </TableCell>
            <TableCell>
              <strong>ʊər</strong>
            </TableCell>
            <TableCell>
              t<strong>our</strong>, C<strong>URE</strong> (/ˈkjʊər/)
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>ʌ</strong>
            </TableCell>
            <TableCell>
              STR<strong>U</strong>T, s<strong>u</strong>ng, <strong>u</strong>
              ntidy
            </TableCell>
            <TableCell>
              <strong>ɜːr</strong>
            </TableCell>
            <TableCell>
              N<strong>UR</strong>SE, bl<strong>ur</strong>ry
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>ʌ</strong>
            </TableCell>
            <TableCell>
              STR<strong>U</strong>T, s<strong>u</strong>ng, <strong>u</strong>
              ntidy
            </TableCell>
            <TableCell>
              <strong>ʌr</strong>
            </TableCell>
            <TableCell>
              h<strong>ur</strong>ry
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
      <Table>
        <TableCaption>A key for weak vowels</TableCaption>
        <TableHeader>
          <TableRow>
            <TableHead>Symbol</TableHead>
            <TableHead>Example</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow>
            <TableCell>
              <strong>ə</strong>
            </TableCell>
            <TableCell>
              COMM<strong>A</strong>, sof<strong>a</strong>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>ɪ</strong>
            </TableCell>
            <TableCell>
              rabb<strong>i</strong>t
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>i</strong>
            </TableCell>
            <TableCell>
              HAPP<strong>Y</strong>, med<strong>i</strong>ocre
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>u</strong>
            </TableCell>
            <TableCell>
              fr<strong>u</strong>ition
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>ər</strong>
            </TableCell>
            <TableCell>
              LETT<strong>ER</strong>, forw<strong>ar</strong>d
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>oʊ</strong>
            </TableCell>
            <TableCell>
              mott<strong>o</strong>, retr<strong>o</strong>active
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>iə</strong>
            </TableCell>
            <TableCell>
              Californ<strong>ia</strong>
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell>
              <strong>uə</strong>
            </TableCell>
            <TableCell>
              infl<strong>ue</strong>nce
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </section>
  );
}
