name: Cypress end-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # Install pnpm dependencies, cache them correctly
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.5.2
      - name: Setup node
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 'latest'
          cache: 'pnpm'
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
        # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: pnpm build
          start: pnpm start
          wait-on: "http://localhost:3000"
          record: true
          parallel: true # Runs test in parallel using settings above
        env:
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          MW_CLIENT_ACCESS_TOKEN: ${{secrets.MW_CLIENT_ACCESS_TOKEN}}
          MERRIAM_WEBSTER_API_KEY: ${{secrets.MERRIAM_WEBSTER_API_KEY}}